"""Validator Council: The Testing & Validation Pipeline."""
import asyncio
from pathlib import Path
import json

from agents.core.base import BaseAgent
from agents.pipeline.test_writer import TestWriter
from agents.pipeline.build_test_agents import TestAgent
from agents.pipeline.review_uploader import ReviewUploader

class ValidatorCouncil(BaseAgent):
    """Orchestrates the third pipeline: from Building Code to a PR/MR."""

    def __init__(self, workspace_name: str):
        super().__init__("ValidatorCouncil", "Orchestrates the Testing & Validation Pipeline.")
        self.workspace_name = workspace_name
        self.planning_dir = Path.home() / "AgentWorkspaces" / workspace_name / ".context" / "planning"
        self.workspace_root = Path.home() / "AgentWorkspaces" / workspace_name

        from hafs.core.registry import agent_registry

        # Pipeline Agents (Dynamic Lookup for Plugin Overrides)
        TestAgentCls = agent_registry.agents.get("TestAgent", TestAgent)
        ReviewUploaderCls = agent_registry.agents.get("ReviewUploader", ReviewUploader)

        self.test_writer = TestWriter()
        self.test_agent = TestAgentCls(str(self.workspace_root))
        self.review_uploader = ReviewUploaderCls(str(self.workspace_root))

    async def run_task(self) -> str:
        """Execute the Validator pipeline."""
        
        # 1. Load Plan and TDD
        plan_path = self.planning_dir / "plan.json"
        tdd_path = self.planning_dir / "TDD.md"
        if not plan_path.exists():
            return "Error: plan.json not found. Run Architect & Builder pipelines first."
            
        plan = json.loads(plan_path.read_text())
        
        # Assume Acceptance Criteria is in the TDD or original prompt
        acceptance_criteria = "Tests should cover all public methods and handle edge cases."
        
        # 2. Generate Tests
        all_files = plan.get("files_to_create", []) + plan.get("files_to_modify", [])
        
        for file_path_str in all_files:
            # Simple heuristic to create a test file path
            test_file_path_str = file_path_str.replace(".py", "_test.py").replace(".proto", "_test.py") # simplistic
            if test_file_path_str == file_path_str: continue # Skip non-testable

            full_path = self.workspace_root / test_file_path_str.lstrip("/")
            
            print(f"[{self.name}] Writing tests for: {file_path_str} -> {full_path}")
            
            test_code = await self.test_writer.run_task(
                file_path=file_path_str,
                acceptance_criteria=acceptance_criteria
            )
            
            full_path.write_text(test_code)

        # 3. Run Tests
        build_targets = plan.get("build_targets", [])
        test_command = f"test {' '.join(build_targets)}" if build_targets else "test"
        
        print(f"[{self.name}] Running tests: {test_command}...")
        test_result = await self.test_agent.run_task(test_command)
        
        print(f"[{self.name}] Test Result:\n{test_result}")
        
        if "FAILED" in test_result or "Build Failed" in test_result:
            return f"Validator Pipeline failed: Tests failed."
            
        # 4. Upload for Review
        print(f"[{self.name}] Uploading for review...")
        review_description = f"Automated feature implementation for: {self.workspace_name}\n\n"
        review_description += "This review was generated by the HAFS autonomous agent pipeline."
        
        upload_result = await self.review_uploader.run_task(review_description)
        
        return f"Validator Pipeline complete! {upload_result}"
