"""HAFS Agents system."""

# Re-export core infrastructure
from agents.core import *

# Re-export autonomy agents
from agents.autonomy import (
    CuriosityExplorerAgent,
    HallucinationWatcherAgent,
    LoopReport,
    SelfHealingAgent,
    SelfImprovementAgent,
)
from agents.knowledge import (
    ALTTPKnowledgeBase,
    ALTTPMultiKBManager,
    UnifiedALTTPKnowledge,
    ALTTPEmbeddingSpecialist,
    ALTTPModuleAnalyzer,
    OracleKnowledgeBase,
    OracleKBBuilder,
    OracleOfSecretsAnalyzer,
    GigaleakKB,
    KnowledgeGraphAgent,
    KBEnhancer,
    RomHackingSpecialist,
)
from agents.pipeline import (
    ArchitectCouncil,
    BuilderCouncil,
    ValidatorCouncil,
    CodeWriter,
    DocWriter,
    TestWriter,
    BuildAgent,
    TestAgent,
    ReviewUploader,
)

# Swarm Agents
from agents.swarm import (
    SwarmCouncil,
    SwarmStatus,
    SwarmStrategist,
    CouncilReviewer,
    DeepDiveDocumenter,
)

from agents.utility import (
    CartographerAgent,
    ChronosAgent,
    ContextVectorAgent,
    DailyBriefingAgent,
    DistributedObservabilityAgent,
    EpisodicMemoryAgent,
    GardenerAgent,
    GeminiHistorianAgent,
    HistoryPipelineAgent,
    MonitorAgent,
    PromptEngineerAgent,
    ReportManagerAgent,
    ScoutAgent,
    ShadowObserver,
    ShellAgent,
    ToolsmithAgent,
    TrendWatcherAgent,
    VisualizerAgent,
)

# Mission Agents
from agents.mission import (
    ResearchMission,
    ResearchDiscovery,
    MissionAgent,
    ALTTPResearchAgent,
    GigaleakAnalysisAgent,
    get_mission_agent,
    DEFAULT_MISSIONS,
)

# Analysis Agents
from agents.analysis import (
    AutonomousContextAgent,
    CodeDescriber,
    CodeKnowledgeBase,
    CodeUnit,
    ContextReportPipeline,
    LanguagePlugin,
    EmbeddingAnalyzer,
    register_plugin,
    get_plugin,
    detect_language,
)

__all__ = [
    "CuriosityExplorerAgent",
    "HallucinationWatcherAgent",
    "LoopReport",
    "SelfHealingAgent",
    "SelfImprovementAgent",
    "ALTTPKnowledgeBase",
    "ALTTPMultiKBManager",
    "UnifiedALTTPKnowledge",
    "ALTTPEmbeddingSpecialist",
    "ALTTPModuleAnalyzer",
    "OracleKnowledgeBase",
    "OracleKBBuilder",
    "OracleOfSecretsAnalyzer",
    "GigaleakKB",
    "KnowledgeGraphAgent",
    "KBEnhancer",
    "RomHackingSpecialist",
    "ArchitectCouncil",
    "BuilderCouncil",
    "ValidatorCouncil",
    "CodeWriter",
    "DocWriter",
    "TestWriter",
    "BuildAgent",
    "TestAgent",
    "ReviewUploader",
    "SwarmCouncil",
    "SwarmStatus",
    "SwarmStrategist",
    "CouncilReviewer",
    "DeepDiveDocumenter",
    "ResearchMission",
    "ResearchDiscovery",
    "MissionAgent",
    "ALTTPResearchAgent",
    "GigaleakAnalysisAgent",
    "get_mission_agent",
    "DEFAULT_MISSIONS",
    "AutonomousContextAgent",
    "CodeDescriber",
    "CodeKnowledgeBase",
    "CodeUnit",
    "ContextReportPipeline",
    "LanguagePlugin",
    "EmbeddingAnalyzer",
    "register_plugin",
    "get_plugin",
    "detect_language",
    "CartographerAgent",
    "ChronosAgent",
    "ContextVectorAgent",
    "DailyBriefingAgent",
    "DistributedObservabilityAgent",
    "EpisodicMemoryAgent",
    "GardenerAgent",
    "GeminiHistorianAgent",
    "HistoryPipelineAgent",
    "MonitorAgent",
    "PromptEngineerAgent",
    "ReportManagerAgent",
    "ScoutAgent",
    "ShadowObserver",
    "ShellAgent",
    "ToolsmithAgent",
    "TrendWatcherAgent",
    "VisualizerAgent",
]
